name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    # paths:
    #   - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name containerdeploytrial

      - name: Pull image from ACR
        run: docker pull containerdeploytrial.azurecr.io/practical_docker_deploy-backend:v1

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_SERVICE_BACKEND }}
          images: containerdeploytrial.azurecr.io/practical_docker_deploy-backend:v1